from app.agents.state import DocSyncState

def generate_openapi_node(state: DocSyncState) -> dict:
    routes = []
    for ast in state.get("parsed_ast", []):
        routes.extend(ast.get("routes", []))

    spec = {
        "openapi": "3.1.0",
        "info": {
            "title": f"{state.get('repo_name', 'API')} Generated Spec",
            "version": state.get("commit_sha", "1.0.0")[:7]
        },
        "paths": {}
    }

    for r in routes:
        path_name = f"/{r.get('type', 'api').lower().replace(' ', '-')}"
        method = r.get("method", "post").lower()
        if path_name not in spec["paths"]:
            spec["paths"][path_name] = {}
        spec["paths"][path_name][method] = {
            "summary": f"Autogenerated doc for {r.get('raw_signature', r.get('signature', 'endpoint'))}",
            "responses": {"200": {"description": "Successful operation"}}
        }

    return {"openapi_spec": spec}